name: 'Setup Golang'

description: 'Setup Golang by using cache'

inputs:
  working-directory:
    description: 'working-directory of go.mod'
    required: true

runs:
  # Golangの環境設定を共通化(compositeを使用)するため、compositeが必須
  using: 'composite'
  steps:
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.working-directory }}/go.mod
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Install Dependencies
        run: go mod download
        shell: bash
        working-directory: ${{ inputs.working-directory }}
