AWSTemplateFormatVersion: 2010-09-09
Description: "VPC Endpoint Stack"

# -------------------------------------
# Metadata
# -------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    # パラメータの並び順
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - Environment
      - Label:
          default: "VPC Endpoint Configuration"
        Parameters:
          - VPCID
          - ECSProtectedSubnet1
          - ECSProtectedSubnet2
          - VPCEndpointSecurityGroupID
          - ProtectedRouteTable1
          - ProtectedRouteTable2

# -------------------------------------
# Parameters
# -------------------------------------
Parameters:
  ProjectName:
    Description: "Enter the project name. (ex: go-rust-comparison)"
    Type: String
    MinLength: 1
    ConstraintDescription: "ProjectName must be entered."
    Default: go-rust-comparison
  Environment:
    Description: "Select the environment name."
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
    ConstraintDescription: "Environment name must be selected."
    Default: dev
  VPCID:
    Description: "Select the VPC ID."
    Type: AWS::EC2::VPC::Id
  ECSProtectedSubnet1:
    Description: "Enter the Subnet ID for ECS in the selected VPC."
    Type: AWS::EC2::Subnet::Id
  ECSProtectedSubnet2:
    Description: "Enter the Subnet ID for ECS in the selected VPC."
    Type: AWS::EC2::Subnet::Id
  VPCEndpointSecurityGroupID:
    Description: "Select the Security Group ID for VPC Endpoint."
    Type: AWS::EC2::SecurityGroup::Id
  ProtectedRouteTable1:
    Description: "Enter the first protected route table ID."
    Type: String
  ProtectedRouteTable2:
    Description: "Enter the second protected route table ID."
    Type: String

# -------------------------------------
# Resources
# -------------------------------------
Resources:
  # -------------------------------------
  # VPC Endpoint
  # -------------------------------------
  # ECSからパラメータストアにアクセスする為のVPC Endpoints
  SSMVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCID
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref ECSProtectedSubnet1
        - !Ref ECSProtectedSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupID
      PrivateDnsEnabled: true

  SSMMessagesVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCID
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref ECSProtectedSubnet1
        - !Ref ECSProtectedSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupID
      PrivateDnsEnabled: true

  EC2MessagesVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCID
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref ECSProtectedSubnet1
        - !Ref ECSProtectedSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupID
      PrivateDnsEnabled: true
  
  # cloudwatch logs VPC endpoint
  LogsVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcId: !Ref VPCID
      SubnetIds:
        - !Ref ECSProtectedSubnet1
        - !Ref ECSProtectedSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupID

  # ECR Private Repository VPC Endpoint
  ECRVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcEndpointType: Interface
      VpcId: !Ref VPCID
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref ECSProtectedSubnet1
        - !Ref ECSProtectedSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupID
  
  ECRAPIEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      VpcEndpointType: Interface
      VpcId: !Ref VPCID
      PrivateDnsEnabled: true
      SubnetIds:
        - !Ref ECSProtectedSubnet1
        - !Ref ECSProtectedSubnet2
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroupID
  
  # S3 VPC Endpoint
  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPCID
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref ProtectedRouteTable1
        - !Ref ProtectedRouteTable2
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3

# -------------------------------------
# Outputs
# -------------------------------------
Outputs:
  SSMVPCEndpoint:
    Value: !Ref SSMVPCEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-SSMVPCEndpoint"
  SSMMessagesVPCEndpoint:
    Value: !Ref SSMMessagesVPCEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-SSMMessagesVPCEndpoint"
  EC2MessagesVPCEndpoint:
    Value: !Ref EC2MessagesVPCEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-EC2MessagesVPCEndpoint"
  LogsEndpoint:
    Value: !Ref LogsVPCEndpoint
    Export:
      Name: !Sub "${ProjectName}-${Environment}-LogsEndpoint"

